### ISSUE TITLE
API call retries happening too quickly

### ISSUE THREAD

**Issue by zakaprov** [golemfactory/yajsapi#193] opened 2021-05-20 13:03 UTC
`yajsapi` version: 0.3.5-alpha.0

```
2021-05-20 12:33:25 [yajsapi] debug: Exception suppressed: Error: Request failed with status code 504
2021-05-20 12:33:25 [yajsapi] debug: API call timed out (attempt 1/5), retrying in 0s
2021-05-20 12:33:30 [yajsapi] debug: Exception suppressed: Error: Request failed with status code 504
2021-05-20 12:33:30 [yajsapi] debug: API call timed out (attempt 2/5), retrying in 0s
2021-05-20 12:33:35 [yajsapi] debug: Exception suppressed: Error: Request failed with status code 504
2021-05-20 12:33:35 [yajsapi] debug: API call timed out (attempt 3/5), giving up after ${duration}ms
2021-05-20 12:33:35 [yajsapi] error: Payment for provider Casa failed; reason: Error: Request failed with status code 504.
```

The retries seem to be happening instantly without any time added between the calls.

Here are the logs from the `yagna` node, as well as `yajsapi` itself:eeee
[blender_yagna_logs.tar.gz](https://github.com/golemfactory/yajsapi/files/6516060/blender_yagna_logs.tar.gz)

**Comment by filipgolem** [comment] 2021-05-20 14:16
The calls happened at:
```
12:33:25
12:33:30
12:33:35
```
The interval between calls is 0ms in both `yapapi` and `yajsapi`.

**Comment by mateuszsrebrny** [comment] 2021-05-20 14:22
So are you saying that it works as intended, but the message is misleading?
or that something should be fixed?

**Comment by filipgolem** [comment] 2021-05-25 10:17
Fixed: https://github.com/golemfactory/yajsapi/pull/195

**Closed by filipgolem** 2021-05-25 10:17 UTC

**Comment by mateuszsrebrny** [comment] 2021-06-01 12:24
didn't see any retries in testnet testing session. Will try once again after mainnet
